### ISSUE TITLE
hard coded dependency in nepomuk-frontend package.json

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/nepomuk#135]
I noticed the route frontend fails on `npm install` due to a hardcoded package path at https://github.com/mapbox/nepomuk/blob/master/frontends/route/package.json#L35.

**Comment by MoKob** [comment]
@andrewharvey thank you for reporting. The project is currently in the process of making its way into a proper open source project. You might stumble across similar issues.

I've prepared a fix using a relative path (for now) since neither the frontend/nor the plugin are in any state to be ready for a release, yet.
